apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: devboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: syednaqvi3/devboard-application:backend-v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: devboard-secret
