events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:80;
    }

    location /api/ {
      rewrite ^/api/(.*)$ /$1 break;
      proxy_pass http://backend:8080;
    }
  }
}
