apiVersion: v1
kind: Secret
metadata:
  name: devboard-secret
  namespace: devboard
type: Opaque
stringData:

  # --------------------
  # PostgreSQL
  # --------------------
  POSTGRES_USER: devboard
  POSTGRES_PASSWORD: devboard
  POSTGRES_DB: devboard

  # --------------------
  # Backend (Go API)
  # --------------------
  BACKEND_PORT: "8080"

  # DB connection (backend uses this)
  POSTGRES_URL: "postgres://devboard:devboard@postgres:5432/devboard?sslmode=disable"

  # --------------------
  # Nginx (if needed later)
  # --------------------
  NGINX_HOST_PORT: "80"
  NGINX_CONTAINER_PORT: "80"
